### ISSUE TITLE
Blacky PC resolution stuck at 640x480

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/impresoras-maintenance-manual-i3#1]
The installation of the OS Lubuntu for Blacky associated computer leaves an annoying trouble with the resolution of the screen, staying stuck at 640x480 with no further options to change.
There are plenty of solutions for it on the web, but the simplest and executed one at 28/09 was:
- Execute in the terminal
  `sudo leafpad /etc/default/grub`
- Uncomment to disable graphical terminal (grub-pc only)
  `#GRUB_TERMINAL=console`
  to
  `GRUB_TERMINAL=console`
- Make it active by running
  `sudo update-grub`
- Reboot the computer

The next bootings will not show the fancy Lubuntu sign at the beggining, but the problem should be fixed.

I propose to include this info in the amazing and extraordinary maintenance guide as part of OS troubles instead of leaving it as a closed issue for a better visibility.
- [x] Include this info in the manual

The info was obtained from the user Sudodus' [ post](https://ubuntuforums.org/showthread.php?t=2260082)  at ubuntuforums.org

**Comment by jgagom** [comment]
Done
