### ISSUE TITLE
Steps per mm problem

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/impresoras-maintenance-manual-i3#2]
Today @Rodriwp and me have been testing Hija Resurrection trying to fix it, these are the problems we have found:

- Excesive amount of material extruded: To solve it we have decreased the extrusion speed (From 250 to 150 -recommended value- and then to 50) It improved the printing quality, but not enough.

- Second layer is printed "inside" the first one, the extrusor does not lift to keep printing.

- Noisy motors

- Printer miss-recognizes dimensions

@Siotma suggested changing some config in Configuración/Configurar Firmware EEPROM in the fields Pasos por mm form 80-80-400-775 to 160-160-8000-315 and it worked perfectly, but these changes although being saved, are dismissed when the printer is reconnected.

Additionally, we have replaced the init files in the PC by the ones in the guide before knowing this info.

Pending to be done: 

- [ ] Make EEPROM changes persistent 

- [ ] Get further information of why this problem happen and document it

**Comment by jgvictores** [comment]
Movido a https://github.com/asrob-uc3m/impresoras-asrob/issues/4
