### ISSUE TITLE
Impresora atascada

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/impresoras-maintenance-manual-i3#3]
La  impresora que no es negra (la Steel) está atascada.

Cuando llegamos el racor de la entrada estaba quitado.

Al intentar colocar el nuevo filamento, nos dimos cuenta de que ya había uno colocado, pero cortado a una altura justo por debajo de los engranajes. Calentando el hotend a 200ºC e intentando sacar / meter el trozo de filamento que hay dentro, el filamento no se mueve en absoluto.

Lo que viene siendo un atasco total.

**Comment by jgvictores** [comment]
Movido a https://github.com/asrob-uc3m/impresoras-asrob/issues/5
